export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_REQUEST_SUCCESS = "GET_PRODUCTS_REQUEST_SUCCESS";
export const GET_PRODUCTS_REQUEST_FAILURE = "GET_PRODUCTS_REQUEST_FAILURE";
export const INSERT_PRODUCT_TO_LOCAL = "INSERT_PRODUCT_TO_LOCAL";
export const REMOVE_PRODUCT_FROM_LOCAL = "REMOVE_PRODUCT_FROM_LOCAL";
export const SORT_PRODUCTS_LIST = "SORT_PRODUCTS_LIST";
